apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgC1rlMZbx0h6isOv+eu1ocVrhmd/PqqoYNPiqkCwl7oxAXmvq4c/eivoxNxgqeDMbkBBlGifirymWhbVOBk/xwcW8LCPR444DuFQGZrFeYM9AOSXl81Zb3d/znk6WfvMft6du2a6YALPCsffJAGhKmfQX57/zc0cGz2mgompJy03WfyEUBrdYFSC014YmlBmUQoXKRv0xJ4vFbMWd9eA7kzVWS0pcVgNn31R2fcRASPzxOShF6EftPocgGTmA6JRk7rAF1TtuAcTgIouySMvX2R1G+vpDTL4EGKV2Q2tZJbhhPenvpcWwAdNlAB38hSz9L6kMAZOMU7q4D6vWv7Wcp2p3nX/46WordPgt9vKejyealhyPaOYL554jZL0P4BqQXHHuqQrMBJaHHIKPIk475WPfPTYiPizbG4Sgek4OPELr7P6KS7+PjBuQ0gmIzFiwzvKFaoH7SKXoU3z5pJtgra0wFTO9YmBPHvbvn+/v1HFRtjveiC8hsTxwAU17kcS5+4IPVlEqLK46fXryQqUQYV58HxwsbiuWfPcuLUY3RoclS5kkGNmwdMSdLUs4wf9IDpM0Cq1qMtUjd9BcnQ4ziKXK9Q5ATRBbMVzn3+bwAaQkKLwxcijVH/l/r4oP9pzuLCHu1AfhWwYVh6SKdGy2Z+V77/XxW87Xi9GME75sqaNK05AWJImBHrTGuQEFoSgJB5J35uFI2UPihCF8ezetpH/pdW71wW2+jW
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

